### ISSUE TITLE
Compatibility with 3.x ?

### ISSUE THREAD

**Issue by LeDistordu** [arkhitech/redmine_timesheet_plugin#59]
App 18984 stdout:
App 18984 stdout:
[ 2015-04-15 19:49:43.9170 15177/7f5bbdfc5700 App/Implementation.cpp:287 ]: Could not spawn process for application /var/redmine: An error occured while starting up the preloader.
  Error ID: fabc71ed
  Error details saved to: /tmp/passenger-error-tn5wJ2.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

<p>If that didn't work, then maybe the problem is that your gems are installed to <code>/var/www/.rvm/gems</code>, while at the same time you set <code>PassengerRuby</code> (Apache) or <code>passenger_ruby</code> (Nginx) to <code>/usr/local/rvm/gems/ruby-2.0.0-p643/wrappers/ruby</code>. Because of the latter, RVM does not load gems from the home directory.</p>

<p>To make RVM load gems from the home directory, you need to set <code>PassengerRuby</code>/<code>passenger_ruby</code> to an RVM wrapper script inside the home directory:</p>

<ol>
  <li>Login as www-data.</li>
  <li>Enable RVM mixed mode by running:
      <pre class="commands">rvm user gemsets</pre></li>
  <li>Run this to find out what to set <code>PassengerRuby</code>/<code>passenger_ruby</code> to:
      <pre class="commands">/usr/local/rvm/gems/ruby-2.0.0-p643/wrappers/ruby \
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/bin/passenger-config --detect-ruby</pre></li>
</ol>

<p>If that didn't help either, then maybe your application is being run under a different environment than it's supposed to. Please check the following:</p>

<ol>
  <li>Is this app supposed to be run as the <code>www-data</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
  <li>Please check whether the correct RVM gemset is being used.</li>
  <li>Sometimes, RVM gemsets may be broken.
      <a href="https://github.com/phusion/passenger/wiki/Resetting-RVM-gemsets">Try resetting them.</a></li>
</ol>

<p>-------- The exception is as follows: -------</p>
Could not find webrat-0.7.3 in any of the sources (Bundler::GemNotFound)
<pre>  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/bundler-1.9.2/lib/bundler/spec_set.rb:92:in `block in materialize&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/bundler-1.9.2/lib/bundler/spec_set.rb:85:in `map!&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/bundler-1.9.2/lib/bundler/spec_set.rb:85:in `materialize&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/bundler-1.9.2/lib/bundler/definition.rb:177:in `specs_for&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/bundler-1.9.2/lib/bundler/definition.rb:166:in `requested_specs&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/bundler-1.9.2/lib/bundler/setup.rb:18:in `&lt;top (required)&gt;&#39;
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require&#39;
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require&#39;
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:278:in `block in run_load_path_setup_code&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:381:in `running_bundler&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:276:in `run_load_path_setup_code&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:99:in `preload_app&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:157:in `&lt;module:App&gt;&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:29:in `&lt;module:PhusionPassenger&gt;&#39;
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:28:in `&lt;main&gt;&#39;</pre>

[ 2015-04-15 19:49:43.9209 15177/7f5bbffff700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 2-154195] Cannot checkout session because a spawning error occurred. The identifier of the error is fabc71ed. Please see earlier logs for details about the error.

**Comment by LeDistordu** [comment]
I have :+1:

**Comment by LeDistordu** [comment]
After 

gem install webrat -v '0.7.3'

No change, i'm noob with ruby / gem .... :o
