### ISSUE TITLE
Redmine 3.4.2 compatibilty

### ISSUE THREAD

**Issue by Cavva79** [arkhitech/redmine_timesheet_plugin#73]
Hi all,

my system engineer installed:
```
Environment:
  Redmine version                3.4.2.stable.16952
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
```
I found this small bug.
```
Started POST "/timesheet/report" for 10.21.70.112 at 2017-08-17 09:11:55 +0200
Processing by TimesheetController#report as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[Removed]", "timesheet"=>{"period"=>"all", "period_type"=>"2", "date_from"=>"2017-08-17", "date_to"=>"2017-08-17", "sort"=>"project", "projects"=>["466"], "activities"=>["8", "9", "11", "10"], "users"=>["418"]}, "commit"=>"Apply"}
  Current user: [Removed] (id=418)
  Rendered plugins/redmine_timesheet_plugin/app/views/timesheet/_form.html.erb (905.5ms)
  Rendered plugins/redmine_timesheet_plugin/app/views/timesheet/report.html.erb within layouts/base (911.0ms)
Completed 500 Internal Server Error in 955ms (ActiveRecord: 348.9ms)

ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
    54:   <%= javascript_include_tag 'timesheet.js', :plugin => 'redmine_timesheet_plugin' %>
    55:   <%= call_hook(:plugin_timesheet_views_timesheets_report_header_tags, { :timesheet => @timesheet }) %>
    56: <% end %>
    57: 
    58: <%= context_menu time_entries_context_menu_path %>
    59: 
    60: <%# TODO: Typo on hook %>
  app/helpers/application_helper.rb:1300:in `context_menu'
  plugins/redmine_timesheet_plugin/app/views/timesheet/report.html.erb:57:in `_plugins_redmine_timesheet_plugin_app_views_timesheet_report_html_erb__593937986361453200_70215260646880'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
I understand that context_menu is important but for now I commented the `<%= context_menu time_entries_context_menu_path %>` line.

I think it is the only issue for compatibility to Redmine 3.4.2

**Comment by Articus** [comment]
Our company was also migrating to Redmine 3.4, so I made PR #74 with miror changes that made this nice plugin compatible with 3.4 for us. PR was even merged to master (thanks to @hishammalik 👍 ) while I was writing this message. Please check if it will work for you as well.

**Comment by Cavva79** [comment]
I tested in my prod_env and in a brand new one but I've same error.
If I right click on the Spent time table I get no url alert on browser
